---
title: "Homework 1"
author: "Natasha Woon"
date: "2026-09-25"
output: github_document
---

# Problem 1 

## Load Packages

```{r}
library(tidyverse)
```

```{r}
data("penguins", package = "palmerpenguins")
```

## Description of Penguins Data set 
The data in this dataset describes different species of penguins across different islands. The 

This data set has `r nrow (penguins)` rows and `r ncol(penguins)` columns.

The mean flipper length is `r mean(pull(penguins, flipper_length_mm), na.rm = TRUE)`mm.

## Scatterplot 

```{r warning = F}
ggplot(data = penguins,
       mapping = aes(bill_length_mm, flipper_length_mm, color = species)) + geom_point()

ggsave("scatterplot.png")
```

# Problem 2

```{r}
set.seed(123)

problem2_df = 
  tibble(
    random_sample = rnorm(10),
    logical_vector = (random_sample > 0),
    character_vector = c("Dog", "Giraffe", "Hamster", "Frog", "Elephant", "Cat", "Moose", "Otter", "Lizard", "Kangaroo"), 
    factor_vector = factor (c("Medium", "Large", "Small", "Small", "Large", "Medium", "Large", "Medium", "Small", "Large"))
  )

problem2_df
```


